### ISSUE TITLE
Instructions to get started

### ISSUE THREAD

**Issue by VLucet** [tnc-ca-geo/animl-frontend#105]
Hi, I am reviewing different platforms for analysing camera trap and yours os obviously very complete.. I was wondering if there was any written instructions on how to deploy the app (including the ML parts).

**Comment by nathanielrindlaub** [comment]
Hey @VLucet - sorry this fell through the cracks. Thanks for reaching out and for your interest. The whole application is built on a microservice architecture, with each service living in it's own repo, and there are instructions for deploying each service to AWS in their respective repos.

If you describe your use case a bit more I'd be happy to talk through whether Animl would be a good fit - and if so, I'd be happy to get you started.

**Comment by nathanielrindlaub** [comment]
Ah, ok I see. I would love to get a completely offline version of this working, and it's both on our road map and in theory possible using something like [LocalStack](https://github.com/localstack) to emulate the AWS services it depends on on a local machine, which is essentially what you'd need. I have not attempted this though and I do think it could get a little thorny, so if you pursue it I'd try to get some help from someone who's well versed in DevOps and AWS infrastructure.

**Comment by VLucet** [comment]
Noted, this is beyond our capacities for now. Thanks for the guidance nevertheless!
