### ISSUE TITLE
Control label and tag creation

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-frontend#124]
"Controlled labels" - limit the labels you can apply so users/volunteers can't apply random labels (for public facing UI of app). Label creation UX similar to github's. Consider also implementing label hierarchy/priority levels ("skunk" > "animal"). Use Radix-color scales as color options.

**Comment by nathanielrindlaub** [comment]
I think we want to disable the ability for even Project Managers to create new labels on the fly w/ the Category Selector (as is currently the case for everyone), because (a) even managers can mistype things & add bad labels and (b) we want to provide some level of color-control.

The main outstanding question here is whether we want to include a hierarchy. 

Pros: hierarchical labels might be useful for data analysis and rolling up child labels into parent labels for classifier training purposes.

Cons: not sure how helpful it is beyond that? Adds another level of cognitive load / decision making on the labeler? Might be a bit annoying to implement?

**Comment by nathanielrindlaub** [comment]
Also worth thinking through implications for ML-generated labels: it would be a bit of an ask of Project Managers to anticipate all the classes/labels their future models might generate and create them ahead of time (and structure them hierarchically if we're doing that). So do labels produced by ML models automatically get shoehorned into projects' "available labels" ?

**Comment by nathanielrindlaub** [comment]
I'm leaning towards keeping labels flat (non-hierarchical) for now. It would add too much complexity with not enough obvious benefit.

**Comment by postfalk** [comment]
Still like the idea to apply filters to certain groups. BUT I guess that is a feature that needs to have a place in the roadmap and should not be implemented ad hoc and hasty.

**Comment by nathanielrindlaub** [comment]
@postfalk what do you mean by "applying filters to certain groups"?

**Comment by postfalk** [comment]
Sorry for being unclear, I mean limiting the labels a volunteer reviewer can apply while reviewing.

**Comment by nathanielrindlaub** [comment]
Oh yes, 100%, that's what this issue is about. I agree I think it's important to implement before opening the door to wider audiences and I've added it to the roadmap.

**Comment by nathanielrindlaub** [comment]
youtube videos on how TrapTagger does this: https://www.youtube.com/watch?v=gw7mCAH7ThU

**Comment by nathanielrindlaub** [comment]
@oliverroick had a good question - should project managers be able to delete labels, and if so, what should happen (do we go through all images in the DB and remove those labels?). Similarly, do we want to allow project managers to rename labels and kick off a label renaming process across all images in the DB?

**Comment by nathanielrindlaub** [comment]
## Updated requirements
I've refined my thoughts on the requirements for this feature after thinking through [image-level tags](https://github.com/tnc-ca-geo/animl-frontend/issues/138#issuecomment-1793160414) a bit more. The requirements are as follows:

### 1. Create a UI so that users can create object-level "Labels"
Object-level labels, as described [here](https://github.com/tnc-ca-geo/animl-frontend/issues/138#issuecomment-1793160414), are the labels that users (and ML models) can apply to objects in images. Their schema will remain the same, but we'll need to create a new collection or some representation of them in the DB (perhaps something like `project.labels`) to store the available labels and their properties. Labels will need to have the following properties and have a UI for setting/editing them:
- **name**
- **color** - this requires a little more thought. I like the interface Github uses for creating new Labels - i.e. a random color generator button but also a field for manually setting the hex value - but I wonder how they're determining whether or not the foreground text should be white or black. Currently we're using a system based on [radix-colors](https://www.radix-ui.com/colors/docs/palette-composition/composing-a-palette) and their scales, which might be another route but could be limiting)
I imagine we'll also need a few un-editable default Labels, including "unknown" and "empty"

### 2. Create a UI so that users can create image-level "Tags"
Tags would require the following:
- **name**
- **permissions level** - allow Project Mangers to restrict some tags (e.g. "retire") to certain roles

### 3. Allow users to edit and delete both Tags and Labels
Editing seems straightforward if we have a single place in the DB where we store the properties and we only reference the tags by immutable Ids, but deleting seems like a bit of a chore to implement on the backend. If it seems too complex we could punt on deleting labels for now. 

### 4. Figure out how to add all potential classes that the available ML models for a given project might return to the labels array. 
[I need to think about this some more]

### 5. Update how we currently `[getLabels](https://github.com/tnc-ca-geo/animl-api/blob/6af51379ffc14235c3cbd32e46cbbaf32b3d09e4/src/api/db/models/Image.js#L73)` on the backend.
We'll no longer need to aggregate every label on every object on every image (yay)

**Comment by nathanielrindlaub** [comment]
After discussion with Nick, we decided to run with option **6.b** above for dealing with labels generated by ML models, but also make color a required property on all ML Model categories so we have some default color to start with when we add ML-model-generated labels to projects' "Label Lists".

**Comment by nathanielrindlaub** [comment]
## Documenting some additional decision making around whether or not we should support "deleting", "disabling", and/or "merging" labels

### Use cases
Use cases for I could think of for “deleting” labels (including all occurrences of their use on images) include:
- PM created a label by accident that they want to delete
- PM changed their mind and decided the label isn't necessary
- PM realized after the fact that the label was redundant (another label that wasn't identical per se actually kind of already represented what they were going for)
- PM may not have realized that they had some ML class/category/label activated that they actually don't need (e.g. 'vehicle' in a place where there just aren't vehicles, so it just adds a lot of work to clean them up). In this case, un-checking the vehicle class in their automation rules to suppress it going forward, and then deleting the vehicle label, should save a ton of work

Use cases for “disabling” labels (preventing their use going forward, but not removing them from images and still allowing users to filter on them):
- PM no longer wants people to be able to label objects with something ("we no longer want users to label 'insects', so let's just remove it altogether so they can't going forward”)
- They changed ML models and the new model has updated classes that they’d like to use going forward; so the PM disables the old classes to make sure reviewers don’t keep using them

Use cases for “merging”:
- For example, say you have “scrub jay” “burrowing owl” and “raven” labels – could you convert them all to “bird”? "Unless I’m not thinking it through completely, I feel like that might obviate the need to full on delete labels, especially if you had a label like “other” that you could just toss unwanted labels into" - Lara)

### Implementation concerns
- For "deleting" and "merging" labels, we would need to iterate over all the images in that project and remove any `image.object.label` that matches. If there are a lot of images that have that label, that would require either a batch task or an SQS queue + separate lambda worker to handle the async job. 
- Fir deleting labels, because objects can have multiple labels, deleting one label out of an image’s label array might produce a bunch of unexpected behaviors
    - for example if an object had a "animal" label and a "rat" label that had been validated by a user, deleting the rat label wouldn't delete the object entirely, it would just display its "animal" label on the frontend
    - we'd also have to be mindful of updating an object's locked state if we were to delete a label that happened to be the only validated label in the object's label array. In that case it should go from locked: true to locked: false. This feels like it’s getting into messy territory 
    - Merging wouldn’t have this issue because we’re swapping one label ID out for another and we presumably would keep all the other locked/validation data the same.


### Decisions
- We're moving forward with implementing "disable" label functionality
- We're supporting a compromise/MVP version of the "delete" label functionality in which we implement the option to delete a label on the front-end, set some total image update threshold (I think we settled on 500 image records), and when a user requests a delete label operation, we count up how many images this would impact and if it's below the threshold and can be run syncronously in the animl-api GraphQL lambda, we run it, if not we return an error that explains the label has been used too much and to contact me to remove it entirely from your project.
- We are going to hold off implementing label "merging" this for now, because (a) it can be accomplished downstream in Excel, (b) it likely would involve manipulating a larger # of images, and thus necessitate async workflow, and c) kind of hard UX to implement on the front end

**Comment by nathanielrindlaub** [comment]
Done!
