### ISSUE TITLE
Plans for video support?

### ISSUE THREAD

**Issue by abfleishman** [tnc-ca-geo/animl-frontend#198]
animl looks like a powerful and important software contribution to the conservation sector.  

Many of our use cases are interested in videos to capture behavioral aspects of animals in the study areas.

Are there any plans to add support for videos from camera traps?

**Comment by nathanielrindlaub** [comment]
@abfleishman at the moment there are no plans to support video I'm afraid. It would be a daunting lift and require a significant amount of additional infrastructure. I wouldn't say it's totally off the table, but for now it's not on our immediate roadmap.
