### ISSUE TITLE
Delete camera configs

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-frontend#229]
Add an item to the camera context menu (to be implemented in #228) to delete the camera (`Project.cameraConfig`) and all images associated with it. If it's a wireless camera, we'd also want to unregister the camera from the project.

This is useful for accidental bulk uploads, accidental wireless camera registrations, etc.

**Comment by postfalk** [comment]
Be careful. People might want to delete the camera but keep the images. Make sure that this does not happen incidental, possible two confirmation checkmarks, one for camera, one for images.

**Comment by jue-henry** [comment]
> Be careful. People might want to delete the camera but keep the images. Make sure that this does not happen incidental, possible two confirmation checkmarks, one for camera, one for images.

I am unsure if we currently support the case where we have images without a camera?
