### ISSUE TITLE
Make views shareable/router

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/animl-frontend#49]
I imagine as interesting images are coming in. People would like to share and discuss them in meetings, IM, and email. Would be great if there was an easy way to reference them in order to look at them together.

**Comment by nathanielrindlaub** [comment]
Definitely. That feature is captured [here](https://github.com/tnc-ca-geo/animl-frontend/issues/3) and [here](https://github.com/tnc-ca-geo/animl-frontend/issues/39).
