### ISSUE TITLE
Can add but not remove "mark empty"

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/animl-frontend#50]
I have playing around the interface somewhat more intensively and found a combination of labels and empty I was not able to correct. I would like to send you a link to the photo but that is a little difficult, see issue tnc-ca-geo/animl-frontend#49.

**Comment by nathanielrindlaub** [comment]
Yeah, making it easier to share images is a high priority feature. 

For now though if you tell me the camera serial number and time stamp I can find it?

**Comment by postfalk** [comment]
Ok, I got how to do this. Might be my bad.

**Comment by nathanielrindlaub** [comment]
Ok I'll close this out for now but feel free to re-open if there's an action to take.
