### ISSUE TITLE
Sort dates from newest to oldest by default

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/animl-frontend#52]
Assuming that people would be interested in new footage

**Comment by nathanielrindlaub** [comment]
True - I also find myself reversing the date created sort order immediately as soon as I get to the app. But one counter argument would be that when looking through a burst of images, it's kind of helpful to have them in chronological order?

I don't know, might be one to ask users about.

**Comment by nathanielrindlaub** [comment]
I'll do this ASAP - the current sort order (oldest to newest) annoying for me too.

**Comment by nathanielrindlaub** [comment]
Done
