### ISSUE TITLE
What is the timezone of the date displayed in the frontend?

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/animl-frontend#54]

**Comment by nathanielrindlaub** [comment]
It's a bit of a mess. Many cameras (including Buckeye) do no include timezone offsets or timezone strings in their EXIF data, so the images' timestamps are being treated as if they're in UTC+0, when in fact they are in UTC-7. You can read through the issue write up in detail [here](https://github.com/tnc-ca-geo/animl-api/issues/35) and [here](https://github.com/tnc-ca-geo/animl-frontend/issues/95). Working on a fix now.
