### ISSUE TITLE
Add public landing page

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-frontend#84]
Will need to develop content. Who might be able to help with this?

**Comment by postfalk** [comment]
I think that might become a priority if we write more and more proposals. Would be great to point there.

**Comment by nathanielrindlaub** [comment]
- [ ] First step will be to update routing to accommodate this. Perhaps https://animl.camera/app is where the application should live, while https://animl.camera/ lands users on a public landing page.

**Comment by nathanielrindlaub** [comment]
- [ ] nav bar
- [ ] hero
- [ ] screenshot
- [ ] features
- [ ] case studies
- [ ] footer

**Comment by nathanielrindlaub** [comment]
make responsive:
- [ ] implement breakpoints, make hero text smaller
- [ ] hamburger menu for nav links

**Comment by nathanielrindlaub** [comment]
Done
